### ISSUE TITLE
Missing segments in ORDRSP D.96A (openedifact-xsd-libs-96A-1.1-SNAPSHOT.jar file)

### ISSUE THREAD

**Issue by tester22** [sapstern/edifactconverter#3]
Hi,

I downloaded the file openedifact-xsd-libs-96A-1.1-SNAPSHOT.jar from sourceforce and the xsd for ordrsp is missing some segments like SG29 and UNT. Do you know what can be causing it?

Do you have any instructions on how to generate the xsd files using this project? It also seems like almost all fields in the D.96A xsds are defined as numeric even when they are defined as alphanumeric in the spec. Do you know any reason for that?

**Comment by sapstern** [comment]
Hi Anton,
found the first bug (nasty little bug).

The ORDRSP xsd should now be fine for the structure.

I will look into the "numeric" bug now.

Thanks for getting in touch.


Best

Matthias

**Comment by sapstern** [comment]
Hi Anton,

found the second bug as well, this was my poor programming.

I have attached the xsd, it should now be ok.

I will publish the changes later on github.

You can find instructions on how to build the converter as well as the xsd
files in the wiki link:

https://github.com/sapstern/edifactconverter/wiki

Thanks again for your valuable feedback.

Best Matthias

**Comment by tester22** [comment]
Hi Matthias,

I generated the xsd's for the D96 formats I need an this looks really good.
Many thanks for this tool!

Kind Regards,
Anton
